
# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python : "3.9"
sphinx:
  configuration: docs/conf.py
 # Vous devrez créer ce fichier dans l'étape suivante

python:
  
  install:
    - requirements: docs/requirements.txt
